### PR TITLE
Feature/JYXB-432 Diffie - Hellman Based Password Encrypted

### PR DESCRIPTION
**Pull request by yuseok-kim-edushare**
This pull request includes significant changes to the authentication flow, particularly the introduction of Diffie-Hellman (DH) key exchange for enhanced security. The changes also involve refactoring existing code and adding new utility functions. Below is a summary of the most important changes:

### Enhancements to Authentication Flow:

* [`apps/client/src/action/auth/OAuthSignInAction.ts`](diffhunk://#diff-9573e00eda5dd77e4a14a1ad5012c392235c5689301b250884f52dbfdf69c083L45-R96): Refactored `signInByAuth` function to include a new `SignInParams` interface and added support for DH key exchange.
* `apps/client/src/app/api/auth/[...nextauth]/authOption.ts`: Updated `authOptions` to attempt DH key exchange before falling back to the traditional sign-in method, and added error handling for both methods. ([apps/client/src/app/api/auth/[...nextauth]/authOption.tsL30-R93](diffhunk://#diff-83092db29e5e0a4bbae9d0e63318697ecb8f1046a9cb1967f82b6f20f7f94628L30-R93))

### Implementation of Diffie-Hellman Key Exchange:

* [`apps/client/src/lib/DHKeyExchange.ts`](diffhunk://#diff-55ae1d13cb8085f59bb63908db562954fbc0e600a8dd71cfdcdc328290cfb084R1-R236): Added a new `DHKeyExchange` class that handles the generation of DH keys, computation of shared secrets, and encryption of passwords.
* [`apps/client/src/action/auth/dhAction.ts`](diffhunk://#diff-019ddb96eec997d053a5ebb9be2385f2500f14e820e82c97452baa87f09ed326R1-R87): Introduced functions `encryptPasswordWithDH` and `destroyDHSession` to manage the DH key exchange process during sign-in.

### Code Refactoring and Cleanup:

* [`apps/client/src/types/auth/OAuthType.ts`](diffhunk://#diff-7ccbe7959b951e483bcef0fdf0ad51b33ff27cd6d195f8e93702b5679c423a27L18-L37): Refactored the `SignInResponse` and `OAuthSignInResponse` interfaces to improve clarity and structure.
* [`apps/client/src/action/auth/OAuthSignInAction.ts`](diffhunk://#diff-9573e00eda5dd77e4a14a1ad5012c392235c5689301b250884f52dbfdf69c083L8-R8): Removed the unused `SignInType` import and added `isValidResponse` for response validation.

These changes collectively enhance the security and maintainability of the authentication process.

### CODE REVIEW

**Comment by yuseok-kim-edushare** [comment]
아, 이거 실행 테스트 한번은 해 봐야 할 거 같아요. 머지는 좀만 기다려 주세요?

**Review by GwendolyNM — APPROVED** [review]
확인했습니다

**Review by jangdebug — APPROVED** [review]
고생하셨습니다

**Comment by yuseok-kim-edushare** [comment]
이제 우리의 로그인은 네이버의 보안 수준에 조금 더 가까워졌네요
(우린 http3는 못 쓰니까 이정도면 꽤 훌륭하지 않을까요?)

**Review by GwendolyNM — APPROVED** [review]
확인했습니다

**Review by sing-u8 — APPROVED** [review]
수고하셨습니다 ~

**Pull request merged**
